<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWxyaacq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWxyaacq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWxyaacq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWxyaacq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWxyaacq\App_KernelDevDebugContainer([
    'container.build_hash' => 'Wxyaacq',
    'container.build_id' => '49a6b365',
    'container.build_time' => 1605527717,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWxyaacq');
